NAME = uls

INC = ./inc/header.h ./inc/macros_header.h 

HEADTMP = ./header.h ./macros_header.h 

SRC = ./main.c \
		./mx_add_c.c \
		./mx_add_cx.c \
		./mx_add_dir_list.c \
		./mx_add_len_date.c \
		./mx_add_len_flag_h.c \
		./mx_add_len_flag_i.c \
		./mx_add_len_flag_o.c \
		./mx_add_len_flag_s.c \
		./mx_add_len_group.c \
		./mx_add_len_links.c \
		./mx_add_len_maj.c \
		./mx_add_len_min.c \
		./mx_add_len_name.c \
		./mx_add_len_size.c \
		./mx_add_len_user.c \
		./mx_add_min_more.c \
		./mx_add_num.c \
		./mx_add_one.c \
		./mx_add_s_i_m.c \
		./mx_add_size_more.c \
		./mx_add_space.c \
		./mx_add_start.c \
		./mx_add_x.c \
		./mx_afterr.c \
		./mx_all.c \
		./mx_all_for_files.c \
		./mx_array_flags.c \
		./mx_bolshe_polovinu.c \
		./mx_buble.c \
		./mx_change.c \
		./mx_chech_end_width.c \
		./mx_check_argv.c \
		./mx_check_argv_tochka.c \
		./mx_check_flags.c \
		./mx_check_g_tochka.c \
		./mx_check_min_maj.c \
		./mx_check_open.c \
		./mx_check_rec.c \
		./mx_check_size.c \
		./mx_check_stat.c \
		./mx_check_x.c \
		./mx_chek_input.c \
		./mx_chek_input_in.c \
		./mx_color_name.c \
		./mx_combine.c \
		./mx_combo.c \
		./mx_combo_x2.c \
		./mx_combo_x3.c \
		./mx_combo_x4.c \
		./mx_count_all_intput.c \
		./mx_count_argv.c \
		./mx_count_files.c \
		./mx_count_lenn_of_time.c \
		./mx_count_mass.c \
		./mx_count_new_argv.c \
		./mx_cre_argv.c \
		./mx_create_f_z.c \
		./mx_cx_max_size.c \
		./mx_cx_tabs.c \
		./mx_else_output_flags.c \
		./mx_error.c \
		./mx_exstra_group.c \
		./mx_extra_line.c \
		./mx_file_info.c \
		./mx_file_or_dir.c \
		./mx_files.c \
		./mx_files_date.c \
		./mx_files_flag_h.c \
		./mx_files_flag_i.c \
		./mx_files_flag_o.c \
		./mx_files_flag_s.c \
		./mx_files_group.c \
		./mx_files_links.c \
		./mx_files_maj.c \
		./mx_files_min.c \
		./mx_files_size.c \
		./mx_files_user.c \
		./mx_find_extend.c \
		./mx_find_f_p.c \
		./mx_find_flag.c \
		./mx_find_ioctl.c \
		./mx_find_true_flag.c \
		./mx_first_check.c \
		./mx_first_e.c \
		./mx_first_group.c \
		./mx_flag_c.c \
		./mx_flag_e.c \
		./mx_flag_fp.c \
		./mx_flag_g.c \
		./mx_flag_h.c \
		./mx_flag_i.c \
		./mx_flag_l.c \
		./mx_flag_m.c \
		./mx_flag_o.c \
		./mx_flag_one.c \
		./mx_flag_s.c \
		./mx_flag_x.c \
		./mx_format_long.c \
		./mx_free.c \
		./mx_full_str.c \
		./mx_full_time.c \
		./mx_get_rev_index.c \
		./mx_get_s.c \
		./mx_group.c \
		./mx_hex.c \
		./mx_konets.c \
		./mx_kostul.c \
		./mx_last_slesh.c \
		./mx_last_slesh_new.c \
		./mx_last_space.c \
		./mx_len_of_array.c \
		./mx_lenn_list.c \
		./mx_lenn_of_the_null.c \
		./mx_link_name.c \
		./mx_list_argv.c \
		./mx_list_files.c \
		./mx_maj.c \
		./mx_mass_for_tochka.c \
		./mx_max_len_date.c \
		./mx_max_len_flag_h.c \
		./mx_max_len_flag_i.c \
		./mx_max_len_flag_o.c \
		./mx_max_len_flag_s.c \
		./mx_max_len_group.c \
		./mx_max_len_links.c \
		./mx_max_len_min.c \
		./mx_max_len_name.c \
		./mx_max_len_size.c \
		./mx_max_len_user.c \
		./mx_min.c \
		./mx_more_than_name.c \
		./mx_name.c \
		./mx_naruto.c \
		./mx_ne_spi.c \
		./mx_new_argv.c \
		./mx_new_mass.c \
		./mx_node_arg.c \
		./mx_node_files.c \
		./mx_output_formats.c \
		./mx_output_m.c \
		./mx_output_one.c \
		./mx_permition.c \
		./mx_permition_new.c \
		./mx_pow_bit.c \
		./mx_pow_bit_double.c \
		./mx_print_all.c \
		./mx_print_default.c \
		./mx_print_diferent_erros.c \
		./mx_print_error.c \
		./mx_print_extend.c \
		./mx_print_files.c \
		./mx_print_m.c \
		./mx_print_mm.c \
		./mx_print_with_flag_x.c \
		./mx_r_uls.c \
		./mx_reverse_index.c \
		./mx_saske_vernis_v_konohy.c \
		./mx_second_flag_c.c \
		./mx_second_flag_x.c \
		./mx_second_group.c \
		./mx_shift_space.c \
		./mx_slesh_en.c \
		./mx_sort_arg.c \
		./mx_sort_arg_file_dir.c \
		./mx_sort_arg_name.c \
		./mx_sort_arg_size.c \
		./mx_sort_arg_time.c \
		./mx_sort_filse_name.c \
		./mx_sort_filse_size.c \
		./mx_sort_filse_time.c \
		./mx_start.c \
		./mx_super_join.c \
		./mx_swap_argv.c \
		./mx_swap_files.c \
		./mx_third_flag_c.c \
		./mx_third_flag_x.c \
		./mx_third_group.c \
		./mx_time_file.c \
		./mx_time_int.c \
		./mx_to_upper_numb.c \
		./mx_total.c \
		./mx_turn_n.c \
		./mx_uls.c \
		./mx_user.c \
		./mx_zero_group.c \

SRCS = ./src/main.c \
		./src/mx_add_c.c \
		./src/mx_add_cx.c \
		./src/mx_add_dir_list.c \
		./src/mx_add_len_date.c \
		./src/mx_add_len_flag_h.c \
		./src/mx_add_len_flag_i.c \
		./src/mx_add_len_flag_o.c \
		./src/mx_add_len_flag_s.c \
		./src/mx_add_len_group.c \
		./src/mx_add_len_links.c \
		./src/mx_add_len_maj.c \
		./src/mx_add_len_min.c \
		./src/mx_add_len_name.c \
		./src/mx_add_len_size.c \
		./src/mx_add_len_user.c \
		./src/mx_add_min_more.c \
		./src/mx_add_num.c \
		./src/mx_add_one.c \
		./src/mx_add_s_i_m.c \
		./src/mx_add_size_more.c \
		./src/mx_add_space.c \
		./src/mx_add_start.c \
		./src/mx_add_x.c \
		./src/mx_afterr.c \
		./src/mx_all.c \
		./src/mx_all_for_files.c \
		./src/mx_array_flags.c \
		./src/mx_bolshe_polovinu.c \
		./src/mx_buble.c \
		./src/mx_change.c \
		./src/mx_chech_end_width.c \
		./src/mx_check_argv.c \
		./src/mx_check_argv_tochka.c \
		./src/mx_check_flags.c \
		./src/mx_check_g_tochka.c \
		./src/mx_check_min_maj.c \
		./src/mx_check_open.c \
		./src/mx_check_rec.c \
		./src/mx_check_size.c \
		./src/mx_check_stat.c \
		./src/mx_check_x.c \
		./src/mx_chek_input.c \
		./src/mx_chek_input_in.c \
		./src/mx_color_name.c \
		./src/mx_combine.c \
		./src/mx_combo.c \
		./src/mx_combo_x2.c \
		./src/mx_combo_x3.c \
		./src/mx_combo_x4.c \
		./src/mx_count_all_intput.c \
		./src/mx_count_argv.c \
		./src/mx_count_files.c \
		./src/mx_count_lenn_of_time.c \
		./src/mx_count_mass.c \
		./src/mx_count_new_argv.c \
		./src/mx_cre_argv.c \
		./src/mx_create_f_z.c \
		./src/mx_cx_max_size.c \
		./src/mx_cx_tabs.c \
		./src/mx_else_output_flags.c \
		./src/mx_error.c \
		./src/mx_exstra_group.c \
		./src/mx_extra_line.c \
		./src/mx_file_info.c \
		./src/mx_file_or_dir.c \
		./src/mx_files.c \
		./src/mx_files_date.c \
		./src/mx_files_flag_h.c \
		./src/mx_files_flag_i.c \
		./src/mx_files_flag_o.c \
		./src/mx_files_flag_s.c \
		./src/mx_files_group.c \
		./src/mx_files_links.c \
		./src/mx_files_maj.c \
		./src/mx_files_min.c \
		./src/mx_files_size.c \
		./src/mx_files_user.c \
		./src/mx_find_extend.c \
		./src/mx_find_f_p.c \
		./src/mx_find_flag.c \
		./src/mx_find_ioctl.c \
		./src/mx_find_true_flag.c \
		./src/mx_first_check.c \
		./src/mx_first_e.c \
		./src/mx_first_group.c \
		./src/mx_flag_c.c \
		./src/mx_flag_e.c \
		./src/mx_flag_fp.c \
		./src/mx_flag_g.c \
		./src/mx_flag_h.c \
		./src/mx_flag_i.c \
		./src/mx_flag_l.c \
		./src/mx_flag_m.c \
		./src/mx_flag_o.c \
		./src/mx_flag_one.c \
		./src/mx_flag_s.c \
		./src/mx_flag_x.c \
		./src/mx_format_long.c \
		./src/mx_free.c \
		./src/mx_full_str.c \
		./src/mx_full_time.c \
		./src/mx_get_rev_index.c \
		./src/mx_get_s.c \
		./src/mx_group.c \
		./src/mx_hex.c \
		./src/mx_konets.c \
		./src/mx_kostul.c \
		./src/mx_last_slesh.c \
		./src/mx_last_slesh_new.c \
		./src/mx_last_space.c \
		./src/mx_len_of_array.c \
		./src/mx_lenn_list.c \
		./src/mx_lenn_of_the_null.c \
		./src/mx_link_name.c \
		./src/mx_list_argv.c \
		./src/mx_list_files.c \
		./src/mx_maj.c \
		./src/mx_mass_for_tochka.c \
		./src/mx_max_len_date.c \
		./src/mx_max_len_flag_h.c \
		./src/mx_max_len_flag_i.c \
		./src/mx_max_len_flag_o.c \
		./src/mx_max_len_flag_s.c \
		./src/mx_max_len_group.c \
		./src/mx_max_len_links.c \
		./src/mx_max_len_min.c \
		./src/mx_max_len_name.c \
		./src/mx_max_len_size.c \
		./src/mx_max_len_user.c \
		./src/mx_min.c \
		./src/mx_more_than_name.c \
		./src/mx_name.c \
		./src/mx_naruto.c \
		./src/mx_ne_spi.c \
		./src/mx_new_argv.c \
		./src/mx_new_mass.c \
		./src/mx_node_arg.c \
		./src/mx_node_files.c \
		./src/mx_output_formats.c \
		./src/mx_output_m.c \
		./src/mx_output_one.c \
		./src/mx_permition.c \
		./src/mx_permition_new.c \
		./src/mx_pow_bit.c \
		./src/mx_pow_bit_double.c \
		./src/mx_print_all.c \
		./src/mx_print_default.c \
		./src/mx_print_diferent_erros.c \
		./src/mx_print_error.c \
		./src/mx_print_extend.c \
		./src/mx_print_files.c \
		./src/mx_print_m.c \
		./src/mx_print_mm.c \
		./src/mx_print_with_flag_x.c \
		./src/mx_r_uls.c \
		./src/mx_reverse_index.c \
		./src/mx_saske_vernis_v_konohy.c \
		./src/mx_second_flag_c.c \
		./src/mx_second_flag_x.c \
		./src/mx_second_group.c \
		./src/mx_shift_space.c \
		./src/mx_slesh_en.c \
		./src/mx_sort_arg.c \
		./src/mx_sort_arg_file_dir.c \
		./src/mx_sort_arg_name.c \
		./src/mx_sort_arg_size.c \
		./src/mx_sort_arg_time.c \
		./src/mx_sort_filse_name.c \
		./src/mx_sort_filse_size.c \
		./src/mx_sort_filse_time.c \
		./src/mx_start.c \
		./src/mx_super_join.c \
		./src/mx_swap_argv.c \
		./src/mx_swap_files.c \
		./src/mx_third_flag_c.c \
		./src/mx_third_flag_x.c \
		./src/mx_third_group.c \
		./src/mx_time_file.c \
		./src/mx_time_int.c \
		./src/mx_to_upper_numb.c \
		./src/mx_total.c \
		./src/mx_turn_n.c \
		./src/mx_uls.c \
		./src/mx_user.c \
		./src/mx_zero_group.c \

OBJ = ./main.o \
		./mx_add_c.o \
		./mx_add_cx.o \
		./mx_add_dir_list.o \
		./mx_add_len_date.o \
		./mx_add_len_flag_h.o \
		./mx_add_len_flag_i.o \
		./mx_add_len_flag_o.o \
		./mx_add_len_flag_s.o \
		./mx_add_len_group.o \
		./mx_add_len_links.o \
		./mx_add_len_maj.o \
		./mx_add_len_min.o \
		./mx_add_len_name.o \
		./mx_add_len_size.o \
		./mx_add_len_user.o \
		./mx_add_min_more.o \
		./mx_add_num.o \
		./mx_add_one.o \
		./mx_add_s_i_m.o \
		./mx_add_size_more.o \
		./mx_add_space.o \
		./mx_add_start.o \
		./mx_add_x.o \
		./mx_afterr.o \
		./mx_all.o \
		./mx_all_for_files.o \
		./mx_array_flags.o \
		./mx_bolshe_polovinu.o \
		./mx_buble.o \
		./mx_change.o \
		./mx_chech_end_width.o \
		./mx_check_argv.o \
		./mx_check_argv_tochka.o \
		./mx_check_flags.o \
		./mx_check_g_tochka.o \
		./mx_check_min_maj.o \
		./mx_check_open.o \
		./mx_check_rec.o \
		./mx_check_size.o \
		./mx_check_stat.o \
		./mx_check_x.o \
		./mx_chek_input.o \
		./mx_chek_input_in.o \
		./mx_color_name.o \
		./mx_combine.o \
		./mx_combo.o \
		./mx_combo_x2.o \
		./mx_combo_x3.o \
		./mx_combo_x4.o \
		./mx_count_all_intput.o \
		./mx_count_argv.o \
		./mx_count_files.o \
		./mx_count_lenn_of_time.o \
		./mx_count_mass.o \
		./mx_count_new_argv.o \
		./mx_cre_argv.o \
		./mx_create_f_z.o \
		./mx_cx_max_size.o \
		./mx_cx_tabs.o \
		./mx_else_output_flags.o \
		./mx_error.o \
		./mx_exstra_group.o \
		./mx_extra_line.o \
		./mx_file_info.o \
		./mx_file_or_dir.o \
		./mx_files.o \
		./mx_files_date.o \
		./mx_files_flag_h.o \
		./mx_files_flag_i.o \
		./mx_files_flag_o.o \
		./mx_files_flag_s.o \
		./mx_files_group.o \
		./mx_files_links.o \
		./mx_files_maj.o \
		./mx_files_min.o \
		./mx_files_size.o \
		./mx_files_user.o \
		./mx_find_extend.o \
		./mx_find_f_p.o \
		./mx_find_flag.o \
		./mx_find_ioctl.o \
		./mx_find_true_flag.o \
		./mx_first_check.o \
		./mx_first_e.o \
		./mx_first_group.o \
		./mx_flag_c.o \
		./mx_flag_e.o \
		./mx_flag_fp.o \
		./mx_flag_g.o \
		./mx_flag_h.o \
		./mx_flag_i.o \
		./mx_flag_l.o \
		./mx_flag_m.o \
		./mx_flag_o.o \
		./mx_flag_one.o \
		./mx_flag_s.o \
		./mx_flag_x.o \
		./mx_format_long.o \
		./mx_free.o \
		./mx_full_str.o \
		./mx_full_time.o \
		./mx_get_rev_index.o \
		./mx_get_s.o \
		./mx_group.o \
		./mx_hex.o \
		./mx_konets.o \
		./mx_kostul.o \
		./mx_last_slesh.o \
		./mx_last_slesh_new.o \
		./mx_last_space.o \
		./mx_len_of_array.o \
		./mx_lenn_list.o \
		./mx_lenn_of_the_null.o \
		./mx_link_name.o \
		./mx_list_argv.o \
		./mx_list_files.o \
		./mx_maj.o \
		./mx_mass_for_tochka.o \
		./mx_max_len_date.o \
		./mx_max_len_flag_h.o \
		./mx_max_len_flag_i.o \
		./mx_max_len_flag_o.o \
		./mx_max_len_flag_s.o \
		./mx_max_len_group.o \
		./mx_max_len_links.o \
		./mx_max_len_min.o \
		./mx_max_len_name.o \
		./mx_max_len_size.o \
		./mx_max_len_user.o \
		./mx_min.o \
		./mx_more_than_name.o \
		./mx_name.o \
		./mx_naruto.o \
		./mx_ne_spi.o \
		./mx_new_argv.o \
		./mx_new_mass.o \
		./mx_node_arg.o \
		./mx_node_files.o \
		./mx_output_formats.o \
		./mx_output_m.o \
		./mx_output_one.o \
		./mx_permition.o \
		./mx_permition_new.o \
		./mx_pow_bit.o \
		./mx_pow_bit_double.o \
		./mx_print_all.o \
		./mx_print_default.o \
		./mx_print_diferent_erros.o \
		./mx_print_error.o \
		./mx_print_extend.o \
		./mx_print_files.o \
		./mx_print_m.o \
		./mx_print_mm.o \
		./mx_print_with_flag_x.o \
		./mx_r_uls.o \
		./mx_reverse_index.o \
		./mx_saske_vernis_v_konohy.o \
		./mx_second_flag_c.o \
		./mx_second_flag_x.o \
		./mx_second_group.o \
		./mx_shift_space.o \
		./mx_slesh_en.o \
		./mx_sort_arg.o \
		./mx_sort_arg_file_dir.o \
		./mx_sort_arg_name.o \
		./mx_sort_arg_size.o \
		./mx_sort_arg_time.o \
		./mx_sort_filse_name.o \
		./mx_sort_filse_size.o \
		./mx_sort_filse_time.o \
		./mx_start.o \
		./mx_super_join.o \
		./mx_swap_argv.o \
		./mx_swap_files.o \
		./mx_third_flag_c.o \
		./mx_third_flag_x.o \
		./mx_third_group.o \
		./mx_time_file.o \
		./mx_time_int.o \
		./mx_to_upper_numb.o \
		./mx_total.o \
		./mx_turn_n.o \
		./mx_uls.o \
		./mx_user.o \
		./mx_zero_group.o \

OBJO = ./obj/main.o \
		./obj/mx_add_c.o \
		./obj/mx_add_cx.o \
		./obj/mx_add_dir_list.o \
		./obj/mx_add_len_date.o \
		./obj/mx_add_len_flag_h.o \
		./obj/mx_add_len_flag_i.o \
		./obj/mx_add_len_flag_o.o \
		./obj/mx_add_len_flag_s.o \
		./obj/mx_add_len_group.o \
		./obj/mx_add_len_links.o \
		./obj/mx_add_len_maj.o \
		./obj/mx_add_len_min.o \
		./obj/mx_add_len_name.o \
		./obj/mx_add_len_size.o \
		./obj/mx_add_len_user.o \
		./obj/mx_add_min_more.o \
		./obj/mx_add_num.o \
		./obj/mx_add_one.o \
		./obj/mx_add_s_i_m.o \
		./obj/mx_add_size_more.o \
		./obj/mx_add_space.o \
		./obj/mx_add_start.o \
		./obj/mx_add_x.o \
		./obj/mx_afterr.o \
		./obj/mx_all.o \
		./obj/mx_all_for_files.o \
		./obj/mx_array_flags.o \
		./obj/mx_bolshe_polovinu.o \
		./obj/mx_buble.o \
		./obj/mx_change.o \
		./obj/mx_chech_end_width.o \
		./obj/mx_check_argv.o \
		./obj/mx_check_argv_tochka.o \
		./obj/mx_check_flags.o \
		./obj/mx_check_g_tochka.o \
		./obj/mx_check_min_maj.o \
		./obj/mx_check_open.o \
		./obj/mx_check_rec.o \
		./obj/mx_check_size.o \
		./obj/mx_check_stat.o \
		./obj/mx_check_x.o \
		./obj/mx_chek_input.o \
		./obj/mx_chek_input_in.o \
		./obj/mx_color_name.o \
		./obj/mx_combine.o \
		./obj/mx_combo.o \
		./obj/mx_combo_x2.o \
		./obj/mx_combo_x3.o \
		./obj/mx_combo_x4.o \
		./obj/mx_count_all_intput.o \
		./obj/mx_count_argv.o \
		./obj/mx_count_files.o \
		./obj/mx_count_lenn_of_time.o \
		./obj/mx_count_mass.o \
		./obj/mx_count_new_argv.o \
		./obj/mx_cre_argv.o \
		./obj/mx_create_f_z.o \
		./obj/mx_cx_max_size.o \
		./obj/mx_cx_tabs.o \
		./obj/mx_else_output_flags.o \
		./obj/mx_error.o \
		./obj/mx_exstra_group.o \
		./obj/mx_extra_line.o \
		./obj/mx_file_info.o \
		./obj/mx_file_or_dir.o \
		./obj/mx_files.o \
		./obj/mx_files_date.o \
		./obj/mx_files_flag_h.o \
		./obj/mx_files_flag_i.o \
		./obj/mx_files_flag_o.o \
		./obj/mx_files_flag_s.o \
		./obj/mx_files_group.o \
		./obj/mx_files_links.o \
		./obj/mx_files_maj.o \
		./obj/mx_files_min.o \
		./obj/mx_files_size.o \
		./obj/mx_files_user.o \
		./obj/mx_find_extend.o \
		./obj/mx_find_f_p.o \
		./obj/mx_find_flag.o \
		./obj/mx_find_ioctl.o \
		./obj/mx_find_true_flag.o \
		./obj/mx_first_check.o \
		./obj/mx_first_e.o \
		./obj/mx_first_group.o \
		./obj/mx_flag_c.o \
		./obj/mx_flag_e.o \
		./obj/mx_flag_fp.o \
		./obj/mx_flag_g.o \
		./obj/mx_flag_h.o \
		./obj/mx_flag_i.o \
		./obj/mx_flag_l.o \
		./obj/mx_flag_m.o \
		./obj/mx_flag_o.o \
		./obj/mx_flag_one.o \
		./obj/mx_flag_s.o \
		./obj/mx_flag_x.o \
		./obj/mx_format_long.o \
		./obj/mx_free.o \
		./obj/mx_full_str.o \
		./obj/mx_full_time.o \
		./obj/mx_get_rev_index.o \
		./obj/mx_get_s.o \
		./obj/mx_group.o \
		./obj/mx_hex.o \
		./obj/mx_konets.o \
		./obj/mx_kostul.o \
		./obj/mx_last_slesh.o \
		./obj/mx_last_slesh_new.o \
		./obj/mx_last_space.o \
		./obj/mx_len_of_array.o \
		./obj/mx_lenn_list.o \
		./obj/mx_lenn_of_the_null.o \
		./obj/mx_link_name.o \
		./obj/mx_list_argv.o \
		./obj/mx_list_files.o \
		./obj/mx_maj.o \
		./obj/mx_mass_for_tochka.o \
		./obj/mx_max_len_date.o \
		./obj/mx_max_len_flag_h.o \
		./obj/mx_max_len_flag_i.o \
		./obj/mx_max_len_flag_o.o \
		./obj/mx_max_len_flag_s.o \
		./obj/mx_max_len_group.o \
		./obj/mx_max_len_links.o \
		./obj/mx_max_len_min.o \
		./obj/mx_max_len_name.o \
		./obj/mx_max_len_size.o \
		./obj/mx_max_len_user.o \
		./obj/mx_min.o \
		./obj/mx_more_than_name.o \
		./obj/mx_name.o \
		./obj/mx_naruto.o \
		./obj/mx_ne_spi.o \
		./obj/mx_new_argv.o \
		./obj/mx_new_mass.o \
		./obj/mx_node_arg.o \
		./obj/mx_node_files.o \
		./obj/mx_output_formats.o \
		./obj/mx_output_m.o \
		./obj/mx_output_one.o \
		./obj/mx_permition.o \
		./obj/mx_permition_new.o \
		./obj/mx_pow_bit.o \
		./obj/mx_pow_bit_double.o \
		./obj/mx_print_all.o \
		./obj/mx_print_default.o \
		./obj/mx_print_diferent_erros.o \
		./obj/mx_print_error.o \
		./obj/mx_print_extend.o \
		./obj/mx_print_files.o \
		./obj/mx_print_m.o \
		./obj/mx_print_mm.o \
		./obj/mx_print_with_flag_x.o \
		./obj/mx_r_uls.o \
		./obj/mx_reverse_index.o \
		./obj/mx_saske_vernis_v_konohy.o \
		./obj/mx_second_flag_c.o \
		./obj/mx_second_flag_x.o \
		./obj/mx_second_group.o \
		./obj/mx_shift_space.o \
		./obj/mx_slesh_en.o \
		./obj/mx_sort_arg.o \
		./obj/mx_sort_arg_file_dir.o \
		./obj/mx_sort_arg_name.o \
		./obj/mx_sort_arg_size.o \
		./obj/mx_sort_arg_time.o \
		./obj/mx_sort_filse_name.o \
		./obj/mx_sort_filse_size.o \
		./obj/mx_sort_filse_time.o \
		./obj/mx_start.o \
		./obj/mx_super_join.o \
		./obj/mx_swap_argv.o \
		./obj/mx_swap_files.o \
		./obj/mx_third_flag_c.o \
		./obj/mx_third_flag_x.o \
		./obj/mx_third_group.o \
		./obj/mx_time_file.o \
		./obj/mx_time_int.o \
		./obj/mx_to_upper_numb.o \
		./obj/mx_total.o \
		./obj/mx_turn_n.o \
		./obj/mx_uls.o \
		./obj/mx_user.o \
		./obj/mx_zero_group.o \

CFLGS = -std=c11 -Wall -Wextra -Wpedantic -Werror

all: install clean

install:
	@make -C libmx -f Makefile install
	@cp $(INC) $(SRCS) .
	@clang $(CFLGS) -c $(SRC)
	@mkdir -pv obj
	@mv $(OBJ) ./obj
	@clang $(CFLGS) $(OBJO) libmx/libmx.a -o $(NAME)

uninstall: clean
	@make -C libmx -f Makefile uninstall
	@rm -rf $(NAME)

clean:
	@make clean -C libmx
	@rm -rf $(OBJO)
	@rm -rf $(SRC)
	@rm -rf $(OBJ)
	@rm -rf $(HEADTMP)
	@rm -rf ./obj

reinstall: uninstall install
